# Generated by Django 3.1.2 on 2020-10-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='followers',
        ),
    ]
